env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - standard
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
rules: {
  no-useless-constructor: 'off',
  no-unused-vars: 'off',
  "@typescript-eslint/no-unused-vars": "error",
  "@typescript-eslint/no-explicit-any": "off",
  "react/react-in-jsx-scope": "off",
}
